language: generic

os:
  - linux
  - osx

env:
  matrix:
    - TRAVIS_PYTHON_VERSION="2.7"
    - TRAVIS_PYTHON_VERSION="3.6"
    - TRAVIS_PYTHON_VERSION="3.7"
  global:
    - MINICONDA_URL_BASE=" https://repo.continuum.io/miniconda/Miniconda3-latest"
    - secure: gsF0tK0qZ1jFk/fjBdwYDMmAmedXFxd0jtFlroEU2vpozsR+a9VKtTCBMOfbP9sLPIDNpoKCbYdfGw91rH4+27fen1o5AIvomTeLcyGbsMxmfDEr0o/WCcx144EWZHi/x5D1QTr0ph3c0QOG8RfJCaWjjKc7cR3MAWVGEjko8og=

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      OS="MacOSX-x86_64"
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install nose numpy pyyaml coveralls basic-modeling-interface -c csdms-stack

install:
  - python setup.py install

before_script:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      conda install openmpi=1.6
    fi
  - conda install -c conda-forge -c csdms-stack dakota hydrotrend
  - dakota --version

script:
  - nosetests --with-doctest --with-coverage --cover-package=dakotathon

after_success:
  - coveralls
